### ISSUE TITLE
Soportar URL con parametros para cambio de pais

### ISSUE THREAD

**Issue by raicerk** [raicerk/Chart-Tech-Trends#36]
Se debe permitir enviar como parametro el pais para cambiar los datos que estan siendo mostrados sin afectar la funcionalidad del selector de pais que esta en el header del sitio, esto permitira compartir el sitio con el pais que corresponda.

Por ejemplo:

* [https://tech-trend.org/cl](https://tech-trend.org/cl)
* [https://tech-trend.org/ar](https://tech-trend.org/ar)
* [https://tech-trend.org/pe](https://tech-trend.org/pe)
* [https://tech-trend.org/co](https://tech-trend.org/co)
* [https://tech-trend.org/mx](https://tech-trend.org/mx)

**Comment by joseglego** [comment]
Incluido en: https://github.com/raicerk/Chart-Tech-Trends/pull/33
