### ISSUE TITLE
Ajustar navbar en la vista mobile

### ISSUE THREAD

**Issue by raicerk** [raicerk/Chart-Tech-Trends#38]
Es necesario ajustar el navbar en la vista mobile para mostrar de mejor manera los paises seleccionados y los datos que van en la cabecera del sitio.

**Comment by saurabh786iit** [comment]
Please assign this to me

**Comment by joseglego** [comment]
Already done in #34

**Comment by raicerk** [comment]
I closed this issue with merge number #34
